<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Navigate to the Edureka application url<br>]]>
    </line>
    <line>
      <![CDATA[Verify Edureka Dashboard Page<br>]]>
    </line>
    <line>
      <![CDATA[Click on SignIn Navigation header<br>]]>
    </line>
    <line>
      <![CDATA[Verify Login is selected as default<br>]]>
    </line>
    <line>
      <![CDATA[Enter incorrect email and correct password<br>]]>
    </line>
    <line>
      <![CDATA[Verify user is not able to Logged in if entered email is incorrect<br>]]>
    </line>
    <line>
      <![CDATA[<a href= 'file://D:/workspace/Edureka_Automation/screenshots/test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword2016-07-05.jpg'target='_blank' ><img src='file://D:/workspace/Edureka_Automation/screenshots/test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword2016-07-05.jpg' height="42" width="42" >test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword2016-07-05</a>]]>
    </line>
  </reporter-output>
  <suite name="VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword" duration-ms="26597" started-at="2016-07-05T14:58:51Z" finished-at="2016-07-05T14:59:18Z">
    <groups>
    </groups>
    <test name="VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword" duration-ms="26597" started-at="2016-07-05T14:58:51Z" finished-at="2016-07-05T14:59:18Z">
      <class name="com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword@6574b225]" name="setUp" is-config="true" duration-ms="5786" started-at="2016-07-05T20:28:51Z" finished-at="2016-07-05T20:28:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword()[pri:0, instance:com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword@6574b225]" name="test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword" duration-ms="19728" started-at="2016-07-05T20:28:57Z" finished-at="2016-07-05T20:29:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.edureka.pages.SignInModalPage.verifyErrorForLogIn(SignInModalPage.java:329)
	at com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword.test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword(VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Navigate to the Edureka application url<br>]]>
            </line>
            <line>
              <![CDATA[Verify Edureka Dashboard Page<br>]]>
            </line>
            <line>
              <![CDATA[Click on SignIn Navigation header<br>]]>
            </line>
            <line>
              <![CDATA[Verify Login is selected as default<br>]]>
            </line>
            <line>
              <![CDATA[Enter incorrect email and correct password<br>]]>
            </line>
            <line>
              <![CDATA[Verify user is not able to Logged in if entered email is incorrect<br>]]>
            </line>
            <line>
              <![CDATA[<a href= 'file://D:/workspace/Edureka_Automation/screenshots/test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword2016-07-05.jpg'target='_blank' ><img src='file://D:/workspace/Edureka_Automation/screenshots/test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword2016-07-05.jpg' height="42" width="42" >test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword2016-07-05</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword -->
        <test-method status="SKIP" signature="test_014serCannotLoggedInWithoutPassword()[pri:0, instance:com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword@6574b225]" name="test_014serCannotLoggedInWithoutPassword" duration-ms="0" started-at="2016-07-05T20:29:17Z" depends-on-methods="com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword.test_013UserCannotLoggedInWithIncorrectEmailAndCorrectPassword" finished-at="2016-07-05T20:29:17Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword.test_014serCannotLoggedInWithoutPassword()[pri:0, instance:com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword@6574b225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword.test_014serCannotLoggedInWithoutPassword()[pri:0, instance:com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword@6574b225] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_014serCannotLoggedInWithoutPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword@6574b225]" name="tearDown" is-config="true" duration-ms="1068" started-at="2016-07-05T20:29:17Z" finished-at="2016-07-05T20:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterMainMethod()[pri:0, instance:com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword@6574b225]" name="afterMainMethod" is-config="true" duration-ms="67" started-at="2016-07-05T20:29:18Z" finished-at="2016-07-05T20:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMainMethod -->
      </class> <!-- com.edureka.scripts.VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword -->
    </test> <!-- VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword -->
  </suite> <!-- VerifyUserCannotLoggedInWithIncorrectEmailAndCorrectPassword -->
</testng-results>
