<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="360LP040" name="com.edureka.scripts.VerifySignUpFromNavigationHeader" tests="2" failures="1" timestamp="5 Jul 2016 14:06:18 GMT" time="91.609" errors="1">
  <testcase name="test_012VerifyLoginWithCorrectEmailAndCorrectPassword" time="0.000" classname="com.edureka.scripts.VerifySignUpFromNavigationHeader">
    <error type="java.lang.Throwable" message="Method VerifySignUpFromNavigationHeader.test_012VerifyLoginWithCorrectEmailAndCorrectPassword()[pri:0, instance:com.edureka.scripts.VerifySignUpFromNavigationHeader@6574b225] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method VerifySignUpFromNavigationHeader.test_012VerifyLoginWithCorrectEmailAndCorrectPassword()[pri:0, instance:com.edureka.scripts.VerifySignUpFromNavigationHeader@6574b225] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </error>
  </testcase> <!-- test_012VerifyLoginWithCorrectEmailAndCorrectPassword -->
  <testcase name="test_01VerifySignUpFromNavigationHeader" time="91.609" classname="com.edureka.scripts.VerifySignUpFromNavigationHeader">
    <failure type="java.lang.AssertionError" message="Element Locator :.//*[@id=&#039;header-II&#039;]/section/nav/div[1]/ul[2]/li[1]/a/span Not found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Element Locator :.//*[@id='header-II']/section/nav/div[1]/ul[2]/li[1]/a/span Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.edureka.util.DriverHelper.clickOn(DriverHelper.java:309)
	at com.edureka.pages.UserHomePage.logout(UserHomePage.java:97)
	at com.edureka.scripts.VerifySignUpFromNavigationHeader.test_01VerifySignUpFromNavigationHeader(VerifySignUpFromNavigationHeader.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- test_01VerifySignUpFromNavigationHeader -->
</testsuite> <!-- com.edureka.scripts.VerifySignUpFromNavigationHeader -->
