<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="360LP048" name="VerifyReferralProcessWhenNoneOfOfferIsPresent" tests="1" failures="1" timestamp="21 Oct 2016 07:45:46 GMT" time="174.274" errors="0">
  <testcase name="test_022VerifyReferralProcessWhenNoneOfOfferIsPresent" time="160.401" classname="com.edureka.referralProcess.VerifyReferralProcessWhenNoneOfOfferIsPresent">
    <failure type="java.lang.AssertionError" message="expected [341] but found [377]">
      <![CDATA[java.lang.AssertionError: expected [341] but found [377]
	at com.edureka.pages.AllCoursesPage.verifyDiscountPriceValue(AllCoursesPage.java:736)
	at com.edureka.referralProcess.VerifyReferralProcessWhenNoneOfOfferIsPresent.test_022VerifyReferralProcessWhenNoneOfOfferIsPresent(VerifyReferralProcessWhenNoneOfOfferIsPresent.java:257)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test_022VerifyReferralProcessWhenNoneOfOfferIsPresent -->
</testsuite> <!-- VerifyReferralProcessWhenNoneOfOfferIsPresent -->
